"""empty message

Revision ID: 326d81c353ef
Revises: d7b0e6587d74
Create Date: 2024-09-15 12:49:22.103376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '326d81c353ef'
down_revision = 'd7b0e6587d74'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
